### ISSUE TITLE
leaves an entity called FABRIC_SIT

### ISSUE THREAD

**Issue by MilkyPandas** [BradBot1/FabricSit#6]
after using the command /sit it left an entity called FABRIC_SIT, you cannot place blocks where that entity is and you cannot kill it.
![Screenshot 2021-07-15 232155](https://user-images.githubusercontent.com/20828049/125886762-079f07d0-828f-4832-8917-98da94031960.png)

**Comment by BradBot1** [comment]
That should not have been left there, can I get your mod list and what you did to make the entity not be killed as it should have been removed once you stopped sitting.

**Comment by MilkyPandas** [comment]
the mod list would be
![image](https://user-images.githubusercontent.com/20828049/126097165-0b982d2a-342c-4c19-b0ac-18939924f7b8.png)
![image](https://user-images.githubusercontent.com/20828049/126097195-c28abf53-577d-4d6d-b34d-9d0d95370a27.png)
![image](https://user-images.githubusercontent.com/20828049/126097232-e2850d51-6be2-4074-a66f-22935865372a.png)
![image](https://user-images.githubusercontent.com/20828049/126097252-587a2ad3-b893-4eaf-b5b9-7683140e028a.png)
![image](https://user-images.githubusercontent.com/20828049/126097278-ed57e63b-7c9d-4715-9958-ce79a037659d.png)
How I made it happen I don't really know, I did /sit and it was working as normal then i tried to break a block and saw that there was an entity there. Sorry I know thats not much of a help.

**Comment by BradBot1** [comment]
While I attempt to find out what happened you can use `/kill @e[name=FABRIC_SEAT,type=minecraft:armor_stand]` to remove it.

**Comment by BradBot1** [comment]
I should have patched this as all chairs that do not have a rider will now automatically kill themselves, if this issue reappears feel free to re-open this issue

**Comment by griffin4cats** [comment]
I don't think this is solved, I just got this error on my server.
![image](https://user-images.githubusercontent.com/62814690/138378696-5a25f822-5a42-4557-9249-892251e4c0d3.png)
Mod list:
![image](https://user-images.githubusercontent.com/62814690/138378770-ad60c3de-0eab-4c47-81e1-7a45f0ab1252.png)
![image](https://user-images.githubusercontent.com/62814690/138378793-29c68cbf-abb0-42b0-bea5-4ff7845d26bb.png)
Yes, i'm using an older version (will update soon) but this should have been fixed in that version.
